name: CI

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v7

            - uses: pnpm/setup@v3
              name: Install pnpm

            - name: Run Typecheck
              run: |
                  pnpm run typecheck

            - name: Run Lint
              run: |
                  pnpm run lint
